### ISSUE TITLE
Can't load plugin: sqlalchemy.dialects:mssql.turbodbc

### ISSUE THREAD

**Issue by DoubleJSK** [dirkjonker/sqlalchemy-turbodbc#6] opened 2019-07-29 22:06 UTC
Hello,

I ran "pip install sqlalchemy-turbodbc".

I'm now attempting to create_engine using the following code:
`engine = create_engine('mssql+turbodbc://SERVERNAME/DBNAME?driver=SQL Server')`

and am receiving the following error:
NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:mssql.turbodbc

Running the same code create_engine with pyodbc works with out issue. i.e. the below code does not throw an error:
`engine = create_engine('mssql+pyodbc://SERVERNAME/DBNAME?driver=SQL Server')`

Perhaps relevant, I'm running Python 3.7.3

Thanks!

**Comment by dirkjonker** [comment] 2019-07-30 09:17
For Python 3 maybe you should use `pip3 install` or are you using a virtualenv? 
Can you list all installed packages (e.g. `pip list`)?

**Comment by dirkjonker** [comment] 2019-08-12 07:52
Hi @DoubleJSK can you provide more information, or tell me if you have got it working yet? Otherwise I have to close this issue, since I cannot help without more information.

**Comment by dirkjonker** [comment] 2019-08-19 08:03
Closing this because I cannot reproduce this issue without additional information.

**Closed as completed by dirkjonker** 2019-08-19 08:03 UTC

**Comment by Sandy921** [comment] 2019-10-06 10:32
i need help for above mentioned issue. the same issue im also facing while creating the exe using pyinstaller. can you help me to fix the issue?
